### ISSUE TITLE
ROW Inspector Dashboard: Street Segment IDs

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-amanda#67]
@TracyLinder I'm looking at the street segments data you provided, and these do not look like street segment IDs. Street segments are typically 8 digits, and these vary in length and do not match any street segment IDs.

The column I'm talking about is called `PROPERTYID`. If I recall correctly these are probably parcel identifiers.

Can you update the query to pull out a street segment ID?

For the script I broke up your xslx into two csvs. This is what I'm looking at:
https://github.com/cityofaustin/atd-amanda/blob/inspector-dash-1/inspector-dash/data/segments.csv

**Comment by johnclary** [comment]
Hmmm. Well, it looks like some of the PROPERTYIDs are valid street segments. E.g, 5052575. But others are are too short in length and/or don't match any known segment.

Any idea what's going on here? Should we just ignore the IDs that are not valid/return no results?

**Comment by TracyLinder** [comment]
@johnclary So 34 of them are not street segment ID's. 1/2 of those are caused by the handful that were migrated in 2006 - those won't be a problem when the data is refreshed. The other few are parcel ID's. It won't happen often, but it *will* happen, so I'll have to update the query to only pull out street segments.

**Comment by TracyLinder** [comment]
I'll remove them from this data set.... the permits (folders) with parcels also have the corresponding street segment, so no harm in removing them.
