### ISSUE TITLE
ATD AMANDA Service Account

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-amanda#87]
CTM Request # 1956463

*Migrated to [atd-data-tech #1886](https://github.com/cityofaustin/atd-data-tech/issues/1886)*

**Comment by johnclary** [comment]
Followed up w/ CTM on this today.

**Comment by johnclary** [comment]
Discussed with AMANDA team. They would prefer to handle ETL for us into an application of our choise. I explained that we need to do a lot of post-processing on the data. We agreed that the best option is to push all of our AMANDA data to the open data portal so that we can access from there. Will discuss with Tracy and get back in touch with CTM.
