### ISSUE TITLE
Product: DAPCZ Agenda Management

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-amanda#93]
## Description
The DAPCZ agenda tool currently in use by Right of Way Management is a non-intuitive Microsoft Word document. Staff and stakeholders need a tool that will foster the coordination the DAPCZ processes depend on. 

### Resources

---
This Github issue represents a project of Austin Transportation's [Data & Technology Services](https://transportation.austintexas.io/about/) team. Project status is documented regularly in the comments below.

*Migrated to [atd-data-tech #1526](https://github.com/cityofaustin/atd-data-tech/issues/1526)*

**Comment by johnclary** [comment]
Email response today:

> A few questions for you:
> - Are the stakeholders all COA employees?
> - How many users (aka, stakeholders) are there, and how often to they change?
> - Does read-only access to the agenda need to be behind a login? I.e., is the content sensitive?
> - How critical is it that people can only add, not delete items? Would an audit trail suffice?
> - How are you managing the agenda today?

**Comment by TracyLinder** [comment]
I'll be attending the DAPCZ meeting on 9/17 to gather more info.

**Comment by TracyLinder** [comment]
**My notes, with feedback from Peter:**

1. DAPCZ Customer contacts a ROW Project Coordinator to get on the DAPCZ agenda. Correct. If they send an email, though, it should go to ROWProjectCoordination@austintexas.gov, not to one of us individually.
2. The ROW Coordinator provides the DAPCZ Customer with instructions, and places them on the DAPCZ agenda. Correct.
3. The ROW Coordinator sends the final DAPCZ Agenda for the month to the stakeholder list 1 week before the DAPCZ Meeting. Incorrect. We must receive an emailed update one week prior to the meeting.  The final DAPCZ agenda goes out the Monday before the meeting, which is on Tuesday.
4. DAPCZ Customers may email a ROW Coordinator ROWProjectCoordination@austintexas.gov with their project update. That’s the only way we should be receiving updates at this point.
5. The ROW Coordinator will update the DAPCZ Agenda with the project updates until the day of the meeting. Incorrect. We will stop updating the Monday before the DAPCZ meeting in order to provide a digital copy to the DAPCZ group.
6. DAPCZ Customers attend the meeting, and provide updates to the project/permit. This is true for those customers who didn’t email us before the meeting, which they’re supposed to do. 
7. The ROW Coordinator attempts to collect project updates that weren't emailed by walking around the room and physically writing the update on his/her printed DAPCZ Agenda. The coordinator will update the agenda document with the comments collected when they return to their office. Correct.
8. DAPCZ Customers are required to sign out of the DAPCZ meeting prior to leaving. DAPCZ customers are required to “sign in” prior to leaving.
9. DAPCZ Customers notify the ROW Coordinator when a project no longer needs to be on the DAPCZ Agenda. Correct. Either through email or at the meeting.
10. To make each month's agenda, the ROW Coordinator opens the DAPCZ Agenda Word doc, and saves a duplicate copy with a new name. Correct.

**Comment by TracyLinder** [comment]
### Email sent today, to Peter, Evelyn, and Paloma:

Hi Peter,

I appreciate you helping me understand this process better. Below are the general next steps for this request. The Dev Huddle is scheduled for 10/1/19. Please let me know if you have any questions. 

1.	Dev Huddle – I meet with DTS developers to provide them an overview of the request, ask them to propose an optimal solution, and estimate how long this will take to develop once work begins.
2.	Backlog – This request is moved to the DTS backlog
3.	Activate Project – This request is pulled into active work during a weekly DTS work review session.
4.	Project Kickoff – I will schedule a project kickoff, where we really dig into what your solution will look like, and when you might get your hands on it. 

All The Best,

**Comment by TracyLinder** [comment]
**Original email from Paloma w/ the request:**

From Paloma:

> Interested in taking our DAPCZ Agenda online.  Making it a shareable, editable, live doc that external stakeholders can access.  Would only want to allow additions not deletions.  Uncertain what program would be best suited for this need.  Would like to invite the Data team member to next month's DAPCZ meeting to get their perspective.  DAPCZ meeting will be Tuesday, June 18th at 10 a.m.

**Comment by TracyLinder** [comment]
### Update:
The Dev Huddle concluded that KNACK is the best solution for this project, and estimated the project to take 2 months.
